In [1]:
import numpy as np
my_list = [1, 2, 3, 4, 5]
arr = np.array(my_list)
print(arr)

[1 2 3 4 5]


In [2]:
type(arr)

numpy.ndarray

In [4]:
import numpy as np

zeros_arr = np.zeros(shape=(3,3))
print(zeros_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [4]:
import numpy as np

ones_arr = np.ones((3, 2))
print(ones_arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [5]:
import numpy as np

random_arr = np.random.rand(4)
print(random_arr)

[0.21770896 0.66970483 0.69039925 0.81422347]


In [6]:
import numpy as np

random_normal_arr = np.random.randn(2, 2)
print(random_normal_arr)

[[-0.31838607 -1.01580318]
 [ 0.10727763  1.13910266]]


In [9]:
import numpy as np
range_arr = np.arange(1, 6)
print(range_arr)


[1 2 3 4 5]


In [10]:
import numpy as np

arr = np.arange(1, 10)
print(arr)
reshaped_arr = np.reshape(arr, (3, 3))
print(reshaped_arr)


[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
dot_product = np.dot(arr1, arr2)
print(dot_product)


[[19 22]
 [43 50]]


In [12]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
sum_result = np.sum(arr)
print(sum_result)


15


In [15]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
mean_result = np.median(arr)
print(mean_result)


3.5
